[build]
builder = "nixpacks"

[deploy]
healthcheckTimeout = 100
restartPolicyType = "on_failure"

[env]
NODE_ENV = "production"
PORT = "8080"

[[services]]
name = "backend"
buildCommand = "cd backend && npm install"
startCommand = "cd backend && node src/runAll.js"
healthcheckPath = "/health"
port = 3001
[[services.env]]
RPC_URL = "https://api.avax.network/ext/bc/C/rpc"
SUBNET_RPC_URLS = '{"DFK":"https://subnets.avax.network/defi-kingdoms/dfk-chain/rpc","Swimmer":"https://subnets.avax.network/swimmer/mainnet/rpc","Dexalot":"https://subnets.avax.network/dexalot/mainnet/rpc"}'
DB_PATH = "/data/icenode.db"
PORT = "3001"

[[services.volumes]]
name = "data"
mountPath = "/data"
newVolume = true

[[services]]
name = "dashboard"
buildCommand = "cd dashboard && rm -rf node_modules && npm install && npm run build"
startCommand = "cd dashboard && npm start"
healthcheckPath = "/"
port = 8080
[[services.env]]
NEXT_PUBLIC_API_URL = "https://icenode-production.up.railway.app"
PORT = "8080"
