[build]
builder = "nixpacks"
buildCommand = "npm run install:all && npm run build"

[deploy]
startCommand = "npm start"
healthcheckPath = "/health"
healthcheckTimeout = 100
restartPolicyType = "on_failure"

[deploy.railway]
name = "icenode"

[env]
NODE_ENV = "production"
PORT = "3001"

[[services]]
name = "api"
envs = []

[[services]]
name = "dashboard"
envs = []
