[build]
builder = "nixpacks"

[deploy]
healthcheckTimeout = 100
restartPolicyType = "on_failure"

[env]
NODE_ENV = "production"
PORT = "8080"

[[services]]
name = "backend"
buildCommand = "cd backend && npm install"
startCommand = "cd backend && npm start"
healthcheckPath = "/health"
port = 3001

[[services]]
name = "dashboard"
buildCommand = "cd dashboard && rm -rf node_modules && npm install && npm run build"
startCommand = "cd dashboard && npm start"
healthcheckPath = "/"
port = 8080
